### PR TITLE
Fixed typos and updated links to point to the Satellite 6.14 documentation pages

### PR DESCRIPTION
**Pull request by ls7ls7**
Hi,

as the title states, there were some typos fixed.

I thought it might be helpful to update the documentation links to 6.14, since 6.12 is EOL by now and should not be deployed anymore and the 6.14 documentation delivers more value. I noted, that there are some mentions about 6.12 in the text of the blog itself, but I don't know if you want it to be like that. 

Greets,
Benny

### CODE REVIEW

**Review by sscheib — APPROVED** [review]
LGTM

**Review by sscheib — CHANGES_REQUESTED** [review]
If replacing the links, please
- Ensure it still contains the referenced documentation
- The mentions of Satellite 6.12 are replaced with 6.14

**Comment by sscheib** [comment]
If cherry-picked:

- `278fbb576c879010e0739a78837576ddb30648b7`
- `fb6247218644955a92831dfde3fbb86713957b51`

(the typo fixes).

For the URLs, please see the proposed changes, thanks! :)

**Comment by sscheib** [comment]
I've further cherry-picked:

- `fdd63d5a4bcf23efc824fa59baf91f64a3025505` (Kickstart reference URL change from `de-de` to `en-us`)
- `b9db9cada8e37d1c73591364e8e2e7f2d8e6fcb2` (Typo fix of `please ensure that`)

**Comment by ls7ls7** [comment]
Hi, 

I double checked all links and they _should_ all point to the equivalent of the 6.14 docs.

Also I changed every appearance of `6.12` I could find.

**Comment by sscheib** [comment]
If you can fix the [`markdownlint` failure](https://github.com/sscheib/sscheib.github.io/actions/runs/8315198445/job/22753270903?pr=35) I'll go ahead and merge 🚀

**Pull request merged**
